### ISSUE TITLE
Unauthorized (HTTP 401)

### ISSUE THREAD

**Issue by justlebeau** [lbraglia/telegram#1]
Hi, 
I have added the appropriate .Renviron file with the token for my bot and have confirmed its presence with Sys.getenv(R_TELEGRAM_BOT_'botname').  When I type:

> bot <- TGBot$new(token = bot_token('botname')) 
> bot$getMe()

I receive the following error:

> Warning message:
> In private$request("getMe") : Unauthorized (HTTP 401).

Perhaps there is a package update that needs to take place?  Below is my session info:

> sessionInfo()
> R version 3.2.3 (2015-12-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252  
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C  
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] telegram_0.5.0 RCurl_1.95-4.7 bitops_1.0-6  
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.3            whisker_0.3-2          magrittr_1.5  
>  [4] bit_1.1-12             munsell_0.4.2          colorspace_1.2-6  
>  [7] lattice_0.20-33        rjson_0.2.15           R6_2.1.1  
> [10] stringr_1.0.0          httr_1.1.0             plyr_1.8.3  
> [13] tools_3.2.3            rCharts_0.4.5          grid_3.2.3  
> [16] DBI_0.3.1              yaml_2.1.13            bit64_0.9-5  
> [19] digest_0.6.9           RJSONIO_1.3-0          twitteR_1.1.9  
> [22] curl_0.9.6             memoise_0.2.1          stringi_1.0-1  
> [25] RGoogleAnalytics_0.1.1 scales_0.3.0           jsonlite_0.9.19  
> [28] lubridate_1.3.3

I have checked the token for accuracy multiple times and it is being entered correctly.  Thank you for your work on this package and any direction you could provide.
~Justin

**Comment by lbraglia** [comment]
hi Justin,

the package version is ok. Are you still experiencing that warning?

i attempted to reproduce it unsuccessfully (with one of my bot, connected to a chat with me only); everything seems fine. 

The only thing i can think now is to try again to check the bot id. Maybe letter l (el) or I (capital i) are quite similar in telegram message (etc). Eg, you could copy/paste the message to a mail, send it to yourself and copy/paste to .Renviron.

Furthermore, do all bot you've created show this warning?

**Comment by justlebeau** [comment]
Thanks for the tip...sorry to waste your time.  Copy/paste worked.  Thanks again for all your work on this.

**Comment by lbraglia** [comment]
ok, fine! best, Luca
