### ISSUE TITLE
SendMessage to Group

### ISSUE THREAD

**Issue by seuriously** [lbraglia/telegram#11]
Is there any way to send message to group because I think the chat id is one-to-one between me and the bot.

thanks

**Comment by ebeneditos** [comment]
You should send it with the parameter chat_id that corresponds to a group. Send any message to the bot from a group and getUpdates to get the chat_id to test it.

**Comment by ariel32** [comment]
Yeah, you can do it same way with one exception: group id starts with minus ("-").

**Comment by lbraglia** [comment]
as pointed out
