### ISSUE TITLE
offset for getUpdates()

### ISSUE THREAD

**Issue by ariel32** [lbraglia/telegram#2]
It is very needed feature, becouse after limit in 100 messages isn't possible get new updates.

**Comment by dayalpuri** [comment]
Hi, I have the same issue as ariel32. According to this post: http://stackoverflow.com/questions/34296374/telegram-bot-api-limit-of-incoming-updates passing update_id of the newest message through offset parameter would solve the problem.
Thanks,
Jan

**Comment by lbraglia** [comment]
Hi , I've updated `getUpdates` to allow `offset` and `limit` params. Also i tested (with a short list of updates) and seems to work.

Could you please test the devel version and let me know how it goes?

**Comment by dayalpuri** [comment]
Hi, it seems to work fine. Thanks a lot!
Jan
