### ISSUE TITLE
sendMessage's disable_web_page_preview

### ISSUE THREAD

**Issue by boscolai1991** [lbraglia/telegram#5]
Dear lbraglia, 

I am quite new to this package but I find it a nice package for a statistician bot developer.

I think you may miss to include disable_web_page_preview in the 'body' inside $sendMessage function. I discover it while trying to set disable_web_page_preview as T and it does not work. 

Thanks for your attention.

Regards,
Bosco

**Comment by lbraglia** [comment]
thanks! i'll check it ASAP. Best Luca
