### ISSUE TITLE
Bot $ sendMessage question

### ISSUE THREAD

**Issue by abinabinabin** [lbraglia/telegram#7]
Bot $ sendMessage ('This is text')
Warning message:
In private $ request ("sendMessage", body = body): Bad Request (HTTP 400).

Warning message Why? Please tell me why

**Comment by Athospd** [comment]
I've experienced the same problem!

**Comment by lbraglia** [comment]
I can't reproduce this 

after setting the package, as explained in https://github.com/lbraglia/telegram, it sends text (and other) correctly.

**Comment by nasir916** [comment]
Hi, 
i got the same problem, however i just want to ask about (R_TELEGRAM_USER_me=123456789). 
is 123456789 is a username of the person we want to chat or bot username?
thanks.

**Comment by seuriously** [comment]
its the message.chat.id once you run the bot$getUpdates().
chat to the bot first so your bot$getUpdates() doesn't return null
